-- 1️⃣ DANH MỤC (CATEGORY) — Cha của PRODUCT (1 - N)
CREATE TABLE CATEGORY (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(100) NOT NULL
);

-- 2️⃣ SẢN PHẨM (PRODUCT) — Thuộc về một CATEGORY (1 - N)
CREATE TABLE PRODUCT (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(100) NOT NULL,
  CATEGORY_ID BIGINT,
  FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID)
);

-- 3️⃣ CHI TIẾT SẢN PHẨM (PRODUCT_DETAIL) — 1 - 1 với PRODUCT
CREATE TABLE PRODUCT_DETAIL (
  PRODUCT_ID BIGINT PRIMARY KEY,
  DESCRIPTION TEXT,
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID)
);

-- 4️⃣ ĐƠN HÀNG (ORDERS)
CREATE TABLE ORDERS (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  CUSTOMER_NAME VARCHAR(100) NOT NULL
);

-- 5️⃣ BẢNG TRUNG GIAN (ORDER_ITEM) — N - N giữa PRODUCT và ORDERS
CREATE TABLE ORDER_ITEM (
  ORDER_ID BIGINT,
  PRODUCT_ID BIGINT,
  QUANTITY INT,
  PRIMARY KEY (ORDER_ID, PRODUCT_ID),
  FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID)
);
