-- 1️⃣ DANH MỤC (CATEGORY) — Cha của PRODUCT (1 - N)
CREATE TABLE CATEGORY (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(100) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_MODIFIED_DATE TIMESTAMP NULL,
  CREATED_BY BIGINT NOT NULL DEFAULT 0,
  LAST_MODIFIED_BY BIGINT NULL
);

-- 2️⃣ SẢN PHẨM (PRODUCT) — Thuộc về một CATEGORY (1 - N)
CREATE TABLE PRODUCT (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(100) NOT NULL,
  CATEGORY_ID BIGINT,
  FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID),
  CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_MODIFIED_DATE TIMESTAMP NULL,
  CREATED_BY BIGINT NOT NULL DEFAULT 0,
  LAST_MODIFIED_BY BIGINT NULL
);

-- 3️⃣ CHI TIẾT SẢN PHẨM (PRODUCT_DETAIL) — 1 - 1 với PRODUCT
CREATE TABLE PRODUCT_DETAIL (
  PRODUCT_ID BIGINT PRIMARY KEY,
  DESCRIPTION TEXT,
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID),
  CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_MODIFIED_DATE TIMESTAMP NULL,
  CREATED_BY BIGINT NOT NULL DEFAULT 0,
  LAST_MODIFIED_BY BIGINT NULL
);

-- 4️⃣ ĐƠN HÀNG (ORDER)
CREATE TABLE ORDER (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  CUSTOMER_NAME VARCHAR(100) NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_MODIFIED_DATE TIMESTAMP NULL,
  CREATED_BY BIGINT NOT NULL DEFAULT 0,
  LAST_MODIFIED_BY BIGINT NULL
);

-- 5️⃣ BẢNG TRUNG GIAN (ORDER_ITEM) — N - N giữa PRODUCT và ORDER
CREATE TABLE ORDER_ITEM (
  ORDER_ID BIGINT,
  PRODUCT_ID BIGINT,
  QUANTITY INT,
  PRIMARY KEY (ORDER_ID, PRODUCT_ID),
  FOREIGN KEY (ORDER_ID) REFERENCES ORDER(ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID),
  CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_MODIFIED_DATE TIMESTAMP NULL,
  CREATED_BY BIGINT NOT NULL DEFAULT 0,
  LAST_MODIFIED_BY BIGINT NULL
);
